// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hr.proto

package com.nekojarashi.grpcjavasample.hr;

public interface EmployeesReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hr.EmployeesReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .hr.Employee employee = 1;</code>
   */
  java.util.List<com.nekojarashi.grpcjavasample.hr.Employee> 
      getEmployeeList();
  /**
   * <code>repeated .hr.Employee employee = 1;</code>
   */
  com.nekojarashi.grpcjavasample.hr.Employee getEmployee(int index);
  /**
   * <code>repeated .hr.Employee employee = 1;</code>
   */
  int getEmployeeCount();
  /**
   * <code>repeated .hr.Employee employee = 1;</code>
   */
  java.util.List<? extends com.nekojarashi.grpcjavasample.hr.EmployeeOrBuilder> 
      getEmployeeOrBuilderList();
  /**
   * <code>repeated .hr.Employee employee = 1;</code>
   */
  com.nekojarashi.grpcjavasample.hr.EmployeeOrBuilder getEmployeeOrBuilder(
      int index);
}
