// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hr.proto

package com.nekojarashi.grpcjavasample.hr;

/**
 * Protobuf type {@code hr.EmployeesReply}
 */
public  final class EmployeesReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:hr.EmployeesReply)
    EmployeesReplyOrBuilder {
  // Use EmployeesReply.newBuilder() to construct.
  private EmployeesReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EmployeesReply() {
    employee_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private EmployeesReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              employee_ = new java.util.ArrayList<com.nekojarashi.grpcjavasample.hr.Employee>();
              mutable_bitField0_ |= 0x00000001;
            }
            employee_.add(
                input.readMessage(com.nekojarashi.grpcjavasample.hr.Employee.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        employee_ = java.util.Collections.unmodifiableList(employee_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nekojarashi.grpcjavasample.hr.HrProto.internal_static_hr_EmployeesReply_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nekojarashi.grpcjavasample.hr.HrProto.internal_static_hr_EmployeesReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nekojarashi.grpcjavasample.hr.EmployeesReply.class, com.nekojarashi.grpcjavasample.hr.EmployeesReply.Builder.class);
  }

  public static final int EMPLOYEE_FIELD_NUMBER = 1;
  private java.util.List<com.nekojarashi.grpcjavasample.hr.Employee> employee_;
  /**
   * <code>repeated .hr.Employee employee = 1;</code>
   */
  public java.util.List<com.nekojarashi.grpcjavasample.hr.Employee> getEmployeeList() {
    return employee_;
  }
  /**
   * <code>repeated .hr.Employee employee = 1;</code>
   */
  public java.util.List<? extends com.nekojarashi.grpcjavasample.hr.EmployeeOrBuilder> 
      getEmployeeOrBuilderList() {
    return employee_;
  }
  /**
   * <code>repeated .hr.Employee employee = 1;</code>
   */
  public int getEmployeeCount() {
    return employee_.size();
  }
  /**
   * <code>repeated .hr.Employee employee = 1;</code>
   */
  public com.nekojarashi.grpcjavasample.hr.Employee getEmployee(int index) {
    return employee_.get(index);
  }
  /**
   * <code>repeated .hr.Employee employee = 1;</code>
   */
  public com.nekojarashi.grpcjavasample.hr.EmployeeOrBuilder getEmployeeOrBuilder(
      int index) {
    return employee_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < employee_.size(); i++) {
      output.writeMessage(1, employee_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < employee_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, employee_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nekojarashi.grpcjavasample.hr.EmployeesReply)) {
      return super.equals(obj);
    }
    com.nekojarashi.grpcjavasample.hr.EmployeesReply other = (com.nekojarashi.grpcjavasample.hr.EmployeesReply) obj;

    boolean result = true;
    result = result && getEmployeeList()
        .equals(other.getEmployeeList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getEmployeeCount() > 0) {
      hash = (37 * hash) + EMPLOYEE_FIELD_NUMBER;
      hash = (53 * hash) + getEmployeeList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nekojarashi.grpcjavasample.hr.EmployeesReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nekojarashi.grpcjavasample.hr.EmployeesReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nekojarashi.grpcjavasample.hr.EmployeesReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nekojarashi.grpcjavasample.hr.EmployeesReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nekojarashi.grpcjavasample.hr.EmployeesReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nekojarashi.grpcjavasample.hr.EmployeesReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nekojarashi.grpcjavasample.hr.EmployeesReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.nekojarashi.grpcjavasample.hr.EmployeesReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nekojarashi.grpcjavasample.hr.EmployeesReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nekojarashi.grpcjavasample.hr.EmployeesReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nekojarashi.grpcjavasample.hr.EmployeesReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code hr.EmployeesReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:hr.EmployeesReply)
      com.nekojarashi.grpcjavasample.hr.EmployeesReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nekojarashi.grpcjavasample.hr.HrProto.internal_static_hr_EmployeesReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nekojarashi.grpcjavasample.hr.HrProto.internal_static_hr_EmployeesReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nekojarashi.grpcjavasample.hr.EmployeesReply.class, com.nekojarashi.grpcjavasample.hr.EmployeesReply.Builder.class);
    }

    // Construct using com.nekojarashi.grpcjavasample.hr.EmployeesReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEmployeeFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (employeeBuilder_ == null) {
        employee_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        employeeBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nekojarashi.grpcjavasample.hr.HrProto.internal_static_hr_EmployeesReply_descriptor;
    }

    public com.nekojarashi.grpcjavasample.hr.EmployeesReply getDefaultInstanceForType() {
      return com.nekojarashi.grpcjavasample.hr.EmployeesReply.getDefaultInstance();
    }

    public com.nekojarashi.grpcjavasample.hr.EmployeesReply build() {
      com.nekojarashi.grpcjavasample.hr.EmployeesReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.nekojarashi.grpcjavasample.hr.EmployeesReply buildPartial() {
      com.nekojarashi.grpcjavasample.hr.EmployeesReply result = new com.nekojarashi.grpcjavasample.hr.EmployeesReply(this);
      int from_bitField0_ = bitField0_;
      if (employeeBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          employee_ = java.util.Collections.unmodifiableList(employee_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.employee_ = employee_;
      } else {
        result.employee_ = employeeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nekojarashi.grpcjavasample.hr.EmployeesReply) {
        return mergeFrom((com.nekojarashi.grpcjavasample.hr.EmployeesReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nekojarashi.grpcjavasample.hr.EmployeesReply other) {
      if (other == com.nekojarashi.grpcjavasample.hr.EmployeesReply.getDefaultInstance()) return this;
      if (employeeBuilder_ == null) {
        if (!other.employee_.isEmpty()) {
          if (employee_.isEmpty()) {
            employee_ = other.employee_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEmployeeIsMutable();
            employee_.addAll(other.employee_);
          }
          onChanged();
        }
      } else {
        if (!other.employee_.isEmpty()) {
          if (employeeBuilder_.isEmpty()) {
            employeeBuilder_.dispose();
            employeeBuilder_ = null;
            employee_ = other.employee_;
            bitField0_ = (bitField0_ & ~0x00000001);
            employeeBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEmployeeFieldBuilder() : null;
          } else {
            employeeBuilder_.addAllMessages(other.employee_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.nekojarashi.grpcjavasample.hr.EmployeesReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.nekojarashi.grpcjavasample.hr.EmployeesReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.nekojarashi.grpcjavasample.hr.Employee> employee_ =
      java.util.Collections.emptyList();
    private void ensureEmployeeIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        employee_ = new java.util.ArrayList<com.nekojarashi.grpcjavasample.hr.Employee>(employee_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.nekojarashi.grpcjavasample.hr.Employee, com.nekojarashi.grpcjavasample.hr.Employee.Builder, com.nekojarashi.grpcjavasample.hr.EmployeeOrBuilder> employeeBuilder_;

    /**
     * <code>repeated .hr.Employee employee = 1;</code>
     */
    public java.util.List<com.nekojarashi.grpcjavasample.hr.Employee> getEmployeeList() {
      if (employeeBuilder_ == null) {
        return java.util.Collections.unmodifiableList(employee_);
      } else {
        return employeeBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .hr.Employee employee = 1;</code>
     */
    public int getEmployeeCount() {
      if (employeeBuilder_ == null) {
        return employee_.size();
      } else {
        return employeeBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .hr.Employee employee = 1;</code>
     */
    public com.nekojarashi.grpcjavasample.hr.Employee getEmployee(int index) {
      if (employeeBuilder_ == null) {
        return employee_.get(index);
      } else {
        return employeeBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .hr.Employee employee = 1;</code>
     */
    public Builder setEmployee(
        int index, com.nekojarashi.grpcjavasample.hr.Employee value) {
      if (employeeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmployeeIsMutable();
        employee_.set(index, value);
        onChanged();
      } else {
        employeeBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .hr.Employee employee = 1;</code>
     */
    public Builder setEmployee(
        int index, com.nekojarashi.grpcjavasample.hr.Employee.Builder builderForValue) {
      if (employeeBuilder_ == null) {
        ensureEmployeeIsMutable();
        employee_.set(index, builderForValue.build());
        onChanged();
      } else {
        employeeBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .hr.Employee employee = 1;</code>
     */
    public Builder addEmployee(com.nekojarashi.grpcjavasample.hr.Employee value) {
      if (employeeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmployeeIsMutable();
        employee_.add(value);
        onChanged();
      } else {
        employeeBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .hr.Employee employee = 1;</code>
     */
    public Builder addEmployee(
        int index, com.nekojarashi.grpcjavasample.hr.Employee value) {
      if (employeeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmployeeIsMutable();
        employee_.add(index, value);
        onChanged();
      } else {
        employeeBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .hr.Employee employee = 1;</code>
     */
    public Builder addEmployee(
        com.nekojarashi.grpcjavasample.hr.Employee.Builder builderForValue) {
      if (employeeBuilder_ == null) {
        ensureEmployeeIsMutable();
        employee_.add(builderForValue.build());
        onChanged();
      } else {
        employeeBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .hr.Employee employee = 1;</code>
     */
    public Builder addEmployee(
        int index, com.nekojarashi.grpcjavasample.hr.Employee.Builder builderForValue) {
      if (employeeBuilder_ == null) {
        ensureEmployeeIsMutable();
        employee_.add(index, builderForValue.build());
        onChanged();
      } else {
        employeeBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .hr.Employee employee = 1;</code>
     */
    public Builder addAllEmployee(
        java.lang.Iterable<? extends com.nekojarashi.grpcjavasample.hr.Employee> values) {
      if (employeeBuilder_ == null) {
        ensureEmployeeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, employee_);
        onChanged();
      } else {
        employeeBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .hr.Employee employee = 1;</code>
     */
    public Builder clearEmployee() {
      if (employeeBuilder_ == null) {
        employee_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        employeeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .hr.Employee employee = 1;</code>
     */
    public Builder removeEmployee(int index) {
      if (employeeBuilder_ == null) {
        ensureEmployeeIsMutable();
        employee_.remove(index);
        onChanged();
      } else {
        employeeBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .hr.Employee employee = 1;</code>
     */
    public com.nekojarashi.grpcjavasample.hr.Employee.Builder getEmployeeBuilder(
        int index) {
      return getEmployeeFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .hr.Employee employee = 1;</code>
     */
    public com.nekojarashi.grpcjavasample.hr.EmployeeOrBuilder getEmployeeOrBuilder(
        int index) {
      if (employeeBuilder_ == null) {
        return employee_.get(index);  } else {
        return employeeBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .hr.Employee employee = 1;</code>
     */
    public java.util.List<? extends com.nekojarashi.grpcjavasample.hr.EmployeeOrBuilder> 
         getEmployeeOrBuilderList() {
      if (employeeBuilder_ != null) {
        return employeeBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(employee_);
      }
    }
    /**
     * <code>repeated .hr.Employee employee = 1;</code>
     */
    public com.nekojarashi.grpcjavasample.hr.Employee.Builder addEmployeeBuilder() {
      return getEmployeeFieldBuilder().addBuilder(
          com.nekojarashi.grpcjavasample.hr.Employee.getDefaultInstance());
    }
    /**
     * <code>repeated .hr.Employee employee = 1;</code>
     */
    public com.nekojarashi.grpcjavasample.hr.Employee.Builder addEmployeeBuilder(
        int index) {
      return getEmployeeFieldBuilder().addBuilder(
          index, com.nekojarashi.grpcjavasample.hr.Employee.getDefaultInstance());
    }
    /**
     * <code>repeated .hr.Employee employee = 1;</code>
     */
    public java.util.List<com.nekojarashi.grpcjavasample.hr.Employee.Builder> 
         getEmployeeBuilderList() {
      return getEmployeeFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.nekojarashi.grpcjavasample.hr.Employee, com.nekojarashi.grpcjavasample.hr.Employee.Builder, com.nekojarashi.grpcjavasample.hr.EmployeeOrBuilder> 
        getEmployeeFieldBuilder() {
      if (employeeBuilder_ == null) {
        employeeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.nekojarashi.grpcjavasample.hr.Employee, com.nekojarashi.grpcjavasample.hr.Employee.Builder, com.nekojarashi.grpcjavasample.hr.EmployeeOrBuilder>(
                employee_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        employee_ = null;
      }
      return employeeBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:hr.EmployeesReply)
  }

  // @@protoc_insertion_point(class_scope:hr.EmployeesReply)
  private static final com.nekojarashi.grpcjavasample.hr.EmployeesReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nekojarashi.grpcjavasample.hr.EmployeesReply();
  }

  public static com.nekojarashi.grpcjavasample.hr.EmployeesReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EmployeesReply>
      PARSER = new com.google.protobuf.AbstractParser<EmployeesReply>() {
    public EmployeesReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new EmployeesReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EmployeesReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EmployeesReply> getParserForType() {
    return PARSER;
  }

  public com.nekojarashi.grpcjavasample.hr.EmployeesReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

