// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hr.proto

package com.nekojarashi.grpcjavasample.hr;

public interface EmployeeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hr.Employee)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional float commissionPct = 1;</code>
   */
  float getCommissionPct();

  /**
   * <code>optional int64 departmentId = 2;</code>
   */
  long getDepartmentId();

  /**
   * <code>optional string email = 3;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>optional string email = 3;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>optional int64 employeeId = 4;</code>
   */
  long getEmployeeId();

  /**
   * <code>optional string firstName = 5;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>optional string firstName = 5;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>optional int64 hireDate = 6;</code>
   */
  long getHireDate();

  /**
   * <code>optional string jobId = 7;</code>
   */
  java.lang.String getJobId();
  /**
   * <code>optional string jobId = 7;</code>
   */
  com.google.protobuf.ByteString
      getJobIdBytes();

  /**
   * <code>optional string lastName = 8;</code>
   */
  java.lang.String getLastName();
  /**
   * <code>optional string lastName = 8;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>optional int64 managerId = 9;</code>
   */
  long getManagerId();

  /**
   * <code>optional string phoneNumber = 10;</code>
   */
  java.lang.String getPhoneNumber();
  /**
   * <code>optional string phoneNumber = 10;</code>
   */
  com.google.protobuf.ByteString
      getPhoneNumberBytes();

  /**
   * <code>optional float salary = 11;</code>
   */
  float getSalary();
}
