// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hr.proto

package com.nekojarashi.grpcjavasample.hr;

/**
 * Protobuf type {@code hr.Employee}
 */
public  final class Employee extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:hr.Employee)
    EmployeeOrBuilder {
  // Use Employee.newBuilder() to construct.
  private Employee(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Employee() {
    commissionPct_ = 0F;
    departmentId_ = 0L;
    email_ = "";
    employeeId_ = 0L;
    firstName_ = "";
    hireDate_ = 0L;
    jobId_ = "";
    lastName_ = "";
    managerId_ = 0L;
    phoneNumber_ = "";
    salary_ = 0F;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Employee(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 13: {

            commissionPct_ = input.readFloat();
            break;
          }
          case 16: {

            departmentId_ = input.readInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            email_ = s;
            break;
          }
          case 32: {

            employeeId_ = input.readInt64();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            firstName_ = s;
            break;
          }
          case 48: {

            hireDate_ = input.readInt64();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            jobId_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            lastName_ = s;
            break;
          }
          case 72: {

            managerId_ = input.readInt64();
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            phoneNumber_ = s;
            break;
          }
          case 93: {

            salary_ = input.readFloat();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nekojarashi.grpcjavasample.hr.HrProto.internal_static_hr_Employee_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nekojarashi.grpcjavasample.hr.HrProto.internal_static_hr_Employee_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nekojarashi.grpcjavasample.hr.Employee.class, com.nekojarashi.grpcjavasample.hr.Employee.Builder.class);
  }

  public static final int COMMISSIONPCT_FIELD_NUMBER = 1;
  private float commissionPct_;
  /**
   * <code>optional float commissionPct = 1;</code>
   */
  public float getCommissionPct() {
    return commissionPct_;
  }

  public static final int DEPARTMENTID_FIELD_NUMBER = 2;
  private long departmentId_;
  /**
   * <code>optional int64 departmentId = 2;</code>
   */
  public long getDepartmentId() {
    return departmentId_;
  }

  public static final int EMAIL_FIELD_NUMBER = 3;
  private volatile java.lang.Object email_;
  /**
   * <code>optional string email = 3;</code>
   */
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <code>optional string email = 3;</code>
   */
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMPLOYEEID_FIELD_NUMBER = 4;
  private long employeeId_;
  /**
   * <code>optional int64 employeeId = 4;</code>
   */
  public long getEmployeeId() {
    return employeeId_;
  }

  public static final int FIRSTNAME_FIELD_NUMBER = 5;
  private volatile java.lang.Object firstName_;
  /**
   * <code>optional string firstName = 5;</code>
   */
  public java.lang.String getFirstName() {
    java.lang.Object ref = firstName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      firstName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string firstName = 5;</code>
   */
  public com.google.protobuf.ByteString
      getFirstNameBytes() {
    java.lang.Object ref = firstName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      firstName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HIREDATE_FIELD_NUMBER = 6;
  private long hireDate_;
  /**
   * <code>optional int64 hireDate = 6;</code>
   */
  public long getHireDate() {
    return hireDate_;
  }

  public static final int JOBID_FIELD_NUMBER = 7;
  private volatile java.lang.Object jobId_;
  /**
   * <code>optional string jobId = 7;</code>
   */
  public java.lang.String getJobId() {
    java.lang.Object ref = jobId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jobId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string jobId = 7;</code>
   */
  public com.google.protobuf.ByteString
      getJobIdBytes() {
    java.lang.Object ref = jobId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jobId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LASTNAME_FIELD_NUMBER = 8;
  private volatile java.lang.Object lastName_;
  /**
   * <code>optional string lastName = 8;</code>
   */
  public java.lang.String getLastName() {
    java.lang.Object ref = lastName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string lastName = 8;</code>
   */
  public com.google.protobuf.ByteString
      getLastNameBytes() {
    java.lang.Object ref = lastName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MANAGERID_FIELD_NUMBER = 9;
  private long managerId_;
  /**
   * <code>optional int64 managerId = 9;</code>
   */
  public long getManagerId() {
    return managerId_;
  }

  public static final int PHONENUMBER_FIELD_NUMBER = 10;
  private volatile java.lang.Object phoneNumber_;
  /**
   * <code>optional string phoneNumber = 10;</code>
   */
  public java.lang.String getPhoneNumber() {
    java.lang.Object ref = phoneNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      phoneNumber_ = s;
      return s;
    }
  }
  /**
   * <code>optional string phoneNumber = 10;</code>
   */
  public com.google.protobuf.ByteString
      getPhoneNumberBytes() {
    java.lang.Object ref = phoneNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      phoneNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SALARY_FIELD_NUMBER = 11;
  private float salary_;
  /**
   * <code>optional float salary = 11;</code>
   */
  public float getSalary() {
    return salary_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (commissionPct_ != 0F) {
      output.writeFloat(1, commissionPct_);
    }
    if (departmentId_ != 0L) {
      output.writeInt64(2, departmentId_);
    }
    if (!getEmailBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
    }
    if (employeeId_ != 0L) {
      output.writeInt64(4, employeeId_);
    }
    if (!getFirstNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, firstName_);
    }
    if (hireDate_ != 0L) {
      output.writeInt64(6, hireDate_);
    }
    if (!getJobIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, jobId_);
    }
    if (!getLastNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, lastName_);
    }
    if (managerId_ != 0L) {
      output.writeInt64(9, managerId_);
    }
    if (!getPhoneNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, phoneNumber_);
    }
    if (salary_ != 0F) {
      output.writeFloat(11, salary_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (commissionPct_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, commissionPct_);
    }
    if (departmentId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, departmentId_);
    }
    if (!getEmailBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
    }
    if (employeeId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, employeeId_);
    }
    if (!getFirstNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, firstName_);
    }
    if (hireDate_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, hireDate_);
    }
    if (!getJobIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, jobId_);
    }
    if (!getLastNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, lastName_);
    }
    if (managerId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, managerId_);
    }
    if (!getPhoneNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, phoneNumber_);
    }
    if (salary_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(11, salary_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nekojarashi.grpcjavasample.hr.Employee)) {
      return super.equals(obj);
    }
    com.nekojarashi.grpcjavasample.hr.Employee other = (com.nekojarashi.grpcjavasample.hr.Employee) obj;

    boolean result = true;
    result = result && (
        java.lang.Float.floatToIntBits(getCommissionPct())
        == java.lang.Float.floatToIntBits(
            other.getCommissionPct()));
    result = result && (getDepartmentId()
        == other.getDepartmentId());
    result = result && getEmail()
        .equals(other.getEmail());
    result = result && (getEmployeeId()
        == other.getEmployeeId());
    result = result && getFirstName()
        .equals(other.getFirstName());
    result = result && (getHireDate()
        == other.getHireDate());
    result = result && getJobId()
        .equals(other.getJobId());
    result = result && getLastName()
        .equals(other.getLastName());
    result = result && (getManagerId()
        == other.getManagerId());
    result = result && getPhoneNumber()
        .equals(other.getPhoneNumber());
    result = result && (
        java.lang.Float.floatToIntBits(getSalary())
        == java.lang.Float.floatToIntBits(
            other.getSalary()));
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + COMMISSIONPCT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getCommissionPct());
    hash = (37 * hash) + DEPARTMENTID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDepartmentId());
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    hash = (37 * hash) + EMPLOYEEID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEmployeeId());
    hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getFirstName().hashCode();
    hash = (37 * hash) + HIREDATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getHireDate());
    hash = (37 * hash) + JOBID_FIELD_NUMBER;
    hash = (53 * hash) + getJobId().hashCode();
    hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getLastName().hashCode();
    hash = (37 * hash) + MANAGERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getManagerId());
    hash = (37 * hash) + PHONENUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getPhoneNumber().hashCode();
    hash = (37 * hash) + SALARY_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getSalary());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nekojarashi.grpcjavasample.hr.Employee parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nekojarashi.grpcjavasample.hr.Employee parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nekojarashi.grpcjavasample.hr.Employee parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nekojarashi.grpcjavasample.hr.Employee parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nekojarashi.grpcjavasample.hr.Employee parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nekojarashi.grpcjavasample.hr.Employee parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nekojarashi.grpcjavasample.hr.Employee parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.nekojarashi.grpcjavasample.hr.Employee parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nekojarashi.grpcjavasample.hr.Employee parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nekojarashi.grpcjavasample.hr.Employee parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nekojarashi.grpcjavasample.hr.Employee prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code hr.Employee}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:hr.Employee)
      com.nekojarashi.grpcjavasample.hr.EmployeeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nekojarashi.grpcjavasample.hr.HrProto.internal_static_hr_Employee_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nekojarashi.grpcjavasample.hr.HrProto.internal_static_hr_Employee_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nekojarashi.grpcjavasample.hr.Employee.class, com.nekojarashi.grpcjavasample.hr.Employee.Builder.class);
    }

    // Construct using com.nekojarashi.grpcjavasample.hr.Employee.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      commissionPct_ = 0F;

      departmentId_ = 0L;

      email_ = "";

      employeeId_ = 0L;

      firstName_ = "";

      hireDate_ = 0L;

      jobId_ = "";

      lastName_ = "";

      managerId_ = 0L;

      phoneNumber_ = "";

      salary_ = 0F;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nekojarashi.grpcjavasample.hr.HrProto.internal_static_hr_Employee_descriptor;
    }

    public com.nekojarashi.grpcjavasample.hr.Employee getDefaultInstanceForType() {
      return com.nekojarashi.grpcjavasample.hr.Employee.getDefaultInstance();
    }

    public com.nekojarashi.grpcjavasample.hr.Employee build() {
      com.nekojarashi.grpcjavasample.hr.Employee result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.nekojarashi.grpcjavasample.hr.Employee buildPartial() {
      com.nekojarashi.grpcjavasample.hr.Employee result = new com.nekojarashi.grpcjavasample.hr.Employee(this);
      result.commissionPct_ = commissionPct_;
      result.departmentId_ = departmentId_;
      result.email_ = email_;
      result.employeeId_ = employeeId_;
      result.firstName_ = firstName_;
      result.hireDate_ = hireDate_;
      result.jobId_ = jobId_;
      result.lastName_ = lastName_;
      result.managerId_ = managerId_;
      result.phoneNumber_ = phoneNumber_;
      result.salary_ = salary_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nekojarashi.grpcjavasample.hr.Employee) {
        return mergeFrom((com.nekojarashi.grpcjavasample.hr.Employee)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nekojarashi.grpcjavasample.hr.Employee other) {
      if (other == com.nekojarashi.grpcjavasample.hr.Employee.getDefaultInstance()) return this;
      if (other.getCommissionPct() != 0F) {
        setCommissionPct(other.getCommissionPct());
      }
      if (other.getDepartmentId() != 0L) {
        setDepartmentId(other.getDepartmentId());
      }
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        onChanged();
      }
      if (other.getEmployeeId() != 0L) {
        setEmployeeId(other.getEmployeeId());
      }
      if (!other.getFirstName().isEmpty()) {
        firstName_ = other.firstName_;
        onChanged();
      }
      if (other.getHireDate() != 0L) {
        setHireDate(other.getHireDate());
      }
      if (!other.getJobId().isEmpty()) {
        jobId_ = other.jobId_;
        onChanged();
      }
      if (!other.getLastName().isEmpty()) {
        lastName_ = other.lastName_;
        onChanged();
      }
      if (other.getManagerId() != 0L) {
        setManagerId(other.getManagerId());
      }
      if (!other.getPhoneNumber().isEmpty()) {
        phoneNumber_ = other.phoneNumber_;
        onChanged();
      }
      if (other.getSalary() != 0F) {
        setSalary(other.getSalary());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.nekojarashi.grpcjavasample.hr.Employee parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.nekojarashi.grpcjavasample.hr.Employee) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private float commissionPct_ ;
    /**
     * <code>optional float commissionPct = 1;</code>
     */
    public float getCommissionPct() {
      return commissionPct_;
    }
    /**
     * <code>optional float commissionPct = 1;</code>
     */
    public Builder setCommissionPct(float value) {
      
      commissionPct_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float commissionPct = 1;</code>
     */
    public Builder clearCommissionPct() {
      
      commissionPct_ = 0F;
      onChanged();
      return this;
    }

    private long departmentId_ ;
    /**
     * <code>optional int64 departmentId = 2;</code>
     */
    public long getDepartmentId() {
      return departmentId_;
    }
    /**
     * <code>optional int64 departmentId = 2;</code>
     */
    public Builder setDepartmentId(long value) {
      
      departmentId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 departmentId = 2;</code>
     */
    public Builder clearDepartmentId() {
      
      departmentId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object email_ = "";
    /**
     * <code>optional string email = 3;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string email = 3;</code>
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      email_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string email = 3;</code>
     */
    public Builder clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
      onChanged();
      return this;
    }
    /**
     * <code>optional string email = 3;</code>
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      email_ = value;
      onChanged();
      return this;
    }

    private long employeeId_ ;
    /**
     * <code>optional int64 employeeId = 4;</code>
     */
    public long getEmployeeId() {
      return employeeId_;
    }
    /**
     * <code>optional int64 employeeId = 4;</code>
     */
    public Builder setEmployeeId(long value) {
      
      employeeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 employeeId = 4;</code>
     */
    public Builder clearEmployeeId() {
      
      employeeId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object firstName_ = "";
    /**
     * <code>optional string firstName = 5;</code>
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string firstName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string firstName = 5;</code>
     */
    public Builder setFirstName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      firstName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string firstName = 5;</code>
     */
    public Builder clearFirstName() {
      
      firstName_ = getDefaultInstance().getFirstName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string firstName = 5;</code>
     */
    public Builder setFirstNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      firstName_ = value;
      onChanged();
      return this;
    }

    private long hireDate_ ;
    /**
     * <code>optional int64 hireDate = 6;</code>
     */
    public long getHireDate() {
      return hireDate_;
    }
    /**
     * <code>optional int64 hireDate = 6;</code>
     */
    public Builder setHireDate(long value) {
      
      hireDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 hireDate = 6;</code>
     */
    public Builder clearHireDate() {
      
      hireDate_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object jobId_ = "";
    /**
     * <code>optional string jobId = 7;</code>
     */
    public java.lang.String getJobId() {
      java.lang.Object ref = jobId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jobId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string jobId = 7;</code>
     */
    public com.google.protobuf.ByteString
        getJobIdBytes() {
      java.lang.Object ref = jobId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jobId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string jobId = 7;</code>
     */
    public Builder setJobId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      jobId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string jobId = 7;</code>
     */
    public Builder clearJobId() {
      
      jobId_ = getDefaultInstance().getJobId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string jobId = 7;</code>
     */
    public Builder setJobIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      jobId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object lastName_ = "";
    /**
     * <code>optional string lastName = 8;</code>
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string lastName = 8;</code>
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string lastName = 8;</code>
     */
    public Builder setLastName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lastName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string lastName = 8;</code>
     */
    public Builder clearLastName() {
      
      lastName_ = getDefaultInstance().getLastName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string lastName = 8;</code>
     */
    public Builder setLastNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lastName_ = value;
      onChanged();
      return this;
    }

    private long managerId_ ;
    /**
     * <code>optional int64 managerId = 9;</code>
     */
    public long getManagerId() {
      return managerId_;
    }
    /**
     * <code>optional int64 managerId = 9;</code>
     */
    public Builder setManagerId(long value) {
      
      managerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 managerId = 9;</code>
     */
    public Builder clearManagerId() {
      
      managerId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object phoneNumber_ = "";
    /**
     * <code>optional string phoneNumber = 10;</code>
     */
    public java.lang.String getPhoneNumber() {
      java.lang.Object ref = phoneNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phoneNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string phoneNumber = 10;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneNumberBytes() {
      java.lang.Object ref = phoneNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phoneNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string phoneNumber = 10;</code>
     */
    public Builder setPhoneNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      phoneNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string phoneNumber = 10;</code>
     */
    public Builder clearPhoneNumber() {
      
      phoneNumber_ = getDefaultInstance().getPhoneNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional string phoneNumber = 10;</code>
     */
    public Builder setPhoneNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      phoneNumber_ = value;
      onChanged();
      return this;
    }

    private float salary_ ;
    /**
     * <code>optional float salary = 11;</code>
     */
    public float getSalary() {
      return salary_;
    }
    /**
     * <code>optional float salary = 11;</code>
     */
    public Builder setSalary(float value) {
      
      salary_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float salary = 11;</code>
     */
    public Builder clearSalary() {
      
      salary_ = 0F;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:hr.Employee)
  }

  // @@protoc_insertion_point(class_scope:hr.Employee)
  private static final com.nekojarashi.grpcjavasample.hr.Employee DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nekojarashi.grpcjavasample.hr.Employee();
  }

  public static com.nekojarashi.grpcjavasample.hr.Employee getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Employee>
      PARSER = new com.google.protobuf.AbstractParser<Employee>() {
    public Employee parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Employee(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Employee> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Employee> getParserForType() {
    return PARSER;
  }

  public com.nekojarashi.grpcjavasample.hr.Employee getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

