// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hr.proto

package com.nekojarashi.grpcjavasample.hr;

public final class HrProto {
  private HrProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hr_EmployeesReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hr_EmployeesReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hr_Employee_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hr_Employee_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010hr.proto\022\002hr\032\033google/protobuf/empty.pr" +
      "oto\"0\n\016EmployeesReply\022\036\n\010employee\030\001 \003(\0132" +
      "\014.hr.Employee\"\330\001\n\010Employee\022\025\n\rcommission" +
      "Pct\030\001 \001(\002\022\024\n\014departmentId\030\002 \001(\003\022\r\n\005email" +
      "\030\003 \001(\t\022\022\n\nemployeeId\030\004 \001(\003\022\021\n\tfirstName\030" +
      "\005 \001(\t\022\020\n\010hireDate\030\006 \001(\003\022\r\n\005jobId\030\007 \001(\t\022\020" +
      "\n\010lastName\030\010 \001(\t\022\021\n\tmanagerId\030\t \001(\003\022\023\n\013p" +
      "honeNumber\030\n \001(\t\022\016\n\006salary\030\013 \001(\0022?\n\002Hr\0229" +
      "\n\tEmployees\022\026.google.protobuf.Empty\032\022.hr" +
      ".EmployeesReply\"\000B3\n!com.nekojarashi.grp",
      "cjavasample.hrB\007HrProtoP\001\242\002\002HRb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_hr_EmployeesReply_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hr_EmployeesReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hr_EmployeesReply_descriptor,
        new java.lang.String[] { "Employee", });
    internal_static_hr_Employee_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hr_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hr_Employee_descriptor,
        new java.lang.String[] { "CommissionPct", "DepartmentId", "Email", "EmployeeId", "FirstName", "HireDate", "JobId", "LastName", "ManagerId", "PhoneNumber", "Salary", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
